### PR TITLE
🐛 FIX: update-notifier deps

### PR DESCRIPTION
**Pull request by armujahid**
This fixes `Error: Cannot find module 'update-notifier'` issue after global installation

### CODE REVIEW

**Comment by armujahid** [comment]
Thanks for creating this. I was previously using your bash PTCL cli: https://github.com/ahmadawais/PTCL-CLI-Bash

**Review by ahmadawais — APPROVED** [review]
LGTM

**Comment by ahmadawais** [comment]
@armujahid thanks for the PR. Was still working on this. Yes, that BASH CLI stopped working since I moved to VDSL so I thought this would be better. Did you try this one? All the options?

**Comment by armujahid** [comment]
Yes It is working perfectly fine. I have tested these options (On VDSL Device: ZXHN H168N V2.2):
1) headless reboot `-xr` (Haven't tested non-headless reboot)
2) xDSL stats (in both headless or non-headless modes)
3) xDSL Screenshot

**Pull request merged**
